<?php
$page = [
    'path' => '/accounting',
    'title' => 'GST Accounting Software with Tally Sync | DotOne',
    'description' => 'GST invoicing, receivables, payables and cash flow visibility in DotOne, with a two-way Tally connector that keeps your books in Tally Prime.',
    'breadcrumbs' => [['Modules', '/modules'], ['Accounting and Tally Sync', '/accounting']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Accounting and Tally Sync',
    'intro' => 'Raise GST invoices, track who owes you and who you owe, and see your funds position from live sales and purchase data. Your books stay in Tally, where your CA already works, kept up to date by the DotOne Tally connector.',
    'highlights' => ['GST invoicing', 'Receivables and payables', 'Cash flow visibility', 'Two-way Tally sync'],
    'capabilities_heading' => 'Billing and accounting software that works with Tally',
    'capabilities_intro' => 'DotOne does not replace Tally. It handles the billing and money tracking that come from daily operations, and posts clean vouchers to Tally so nobody keys the same invoice twice.',
    'capabilities' => [
        ['doc', 'GST invoicing', 'Raise GST invoices and credit notes from sales orders, with tax worked out from your item and HSN setup.'],
        ['trend', 'Receivables tracking', 'See outstanding amounts by customer from your sales invoices and receipts.'],
        ['cart', 'Payables tracking', 'See what you owe each vendor from purchase bills and payments.'],
        ['rupee', 'Funds and cash flow', 'One view of money coming in and going out, built from live sales and purchase data.'],
        ['link', 'Two-way Tally connector', 'Masters sync both ways. Sales, purchase, payment, receipt and journal vouchers push to Tally Prime or Tally ERP 9.'],
        ['box', 'Optional stock journals', 'Material issue and finished goods receipt can post to Tally as stock journals, so stock value in Tally follows the shopfloor.'],
    ],
    'workflow_intro' => 'Transactions start in DotOne where the work happens. The connector posts them to Tally, where your accountant closes the books.',
    'workflow' => [
        ['Bill', 'A GST invoice or purchase bill is created from the sales or purchase order.'],
        ['Approve', 'The transaction is approved in DotOne.'],
        ['Track', 'Receivables, payables and the funds view update straight away.'],
        ['Sync', 'The connector posts the voucher to Tally with mapped ledgers and GST.'],
        ['Close', 'Your CA runs GST returns and P&L from Tally, with no re-entry.'],
    ],
    'reports' => [
        'Customer outstanding and receivables ageing',
        'Vendor payables by due date',
        'Funds and cash flow summary',
        'Sales and purchase invoice registers',
        'GST summary by tax rate',
        'Tally sync log with voucher references',
    ],
    'connected_intro' => 'Accounting is fed by sales, purchase and inventory, so invoices, bills and stock movements reach Tally without a second entry.',
    'connected' => ['sales-management', 'purchase-management', 'inventory-management', 'payroll', 'reports-analytics'],
    'agent' => null,
    'agent_questions' => [],
    'faq' => [
        ['Does DotOne replace Tally?', 'No. DotOne handles GST invoicing, receivables, payables and cash flow visibility from your operations. Your books, GST returns and final accounts stay in Tally, kept up to date by the DotOne Tally connector.'],
        ['Which Tally versions does the connector support?', 'Tally Prime and Tally ERP 9. Tally Prime is recommended for current GST features. See the [Tally integration guide](/integrations/tally) for the full setup.'],
        ['What syncs between DotOne and Tally?', 'Customer, vendor, item and ledger masters sync both ways. Sales and purchase invoices, credit and debit notes, payments, receipts and journals push from DotOne to Tally. Stock journals are optional. See the [Tally integration guide](/integrations/tally) for the full list.'],
        ['What happens if a voucher fails to sync?', 'It stays in an error queue with the reason, such as a missing ledger. You fix the cause and retry, and the same voucher never posts twice.'],
    ],
    'cta_heading' => 'See DotOne and Tally working together',
    'cta_text' => 'In a 30-minute demo we raise a GST invoice in DotOne and show how it reaches your Tally company as a voucher.',
];
include __DIR__ . '/includes/templates/module.php';
