<?php
$page = [
    'path' => '/business-analytics',
    'title' => 'Business Analytics Software | DotOne',
    'description' => 'Business analytics software for manufacturers. See trends, compare plants and periods, drill into the detail and track KPIs from live DotOne ERP data.',
    'breadcrumbs' => [['Modules', '/modules'], ['Business Analytics', '/business-analytics']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Business Analytics Software',
    'intro' => 'Standard reports tell you what happened. Business analytics in DotOne helps you see why: how a number has moved over time, how one plant compares with another, and which orders, items or customers are behind a change.',
    'highlights' => ['Trends over time', 'Plant and period comparison', 'Drill-down', 'KPI tracking'],
    'capabilities_heading' => 'Look past the monthly total',
    'capabilities_intro' => 'Analytics reads the same live records as every other module, so you can follow a question from the summary down to the transaction.',
    'capabilities' => [
        ['trend', 'Trends', 'See how sales, stock, production and purchase figures move week by week or month by month.'],
        ['factory', 'Comparisons across plants', 'Put plants, warehouses or branches side by side for the same period and spot where one is behind.'],
        ['chart', 'Period comparisons', 'Compare this month with last month, or this quarter with the same quarter last year.'],
        ['eye', 'Drill-down', 'Open any total to see the customers, items, orders or job cards behind it.'],
        ['spark', 'KPIs', 'Track the measures your management meeting uses, such as sales, margins, stock value and on-time dispatch.'],
        ['chat', 'Ask in plain language', 'Ask the Reporting AI Agent a question and get the table or summary built from live data.'],
    ],
    'workflow_intro' => 'Analytics in DotOne starts from a question and ends with a follow-up, not a spreadsheet.',
    'workflow' => [
        ['Ask', 'Start from a KPI or type a question for the Reporting Agent.'],
        ['See the trend', 'Look at how the number has moved over recent periods.'],
        ['Compare', 'Put plants, teams or periods side by side.'],
        ['Drill down', 'Open the total to find the items or customers behind the change.'],
        ['Act', 'Share the view with the person who needs to follow up.'],
    ],
    'reports' => [
        'Sales trend by customer, item and region',
        'Plant-wise comparison of output and sales',
        'Period on period comparison',
        'Margin by product group',
        'KPI summary for management',
        'Stock value trend by warehouse',
    ],
    'connected_intro' => 'Analytics draws on every module. Standard registers and MIS live in Reports and Analytics; this module is for digging into the numbers.',
    'connected' => ['reports-analytics', 'sales-management', 'inventory-management', 'production-management', 'purchase-management', 'finance-management'],
    'agent' => 'reporting',
    'agent_questions' => [
        'How have PVC pipe sales moved over the last six months?',
        'Compare dispatch on time between Plant 1 and Plant 2 this quarter.',
        'Which customers bought less this quarter than last?',
    ],
    'faq' => [
        ['How is business analytics different from reports?', '[Reports and Analytics](/reports-analytics) gives you the standard registers, dashboards and MIS. Business analytics is for looking at trends, comparing plants and periods and drilling into the detail behind a number.'],
        ['Can we compare plants?', 'Yes. DotOne supports multi-plant reporting, so you can compare plants side by side or look at one on its own.'],
        ['Do we need a separate BI tool?', 'For most day-to-day questions, no. Analytics works on the live data already in DotOne. If you use a BI tool today, we can discuss how it fits.'],
        ['Can we just ask a question?', 'Yes. The [Reporting AI Agent](/ai-agents/reporting) answers questions in plain language and builds the report from live ERP data.'],
    ],
    'cta_heading' => 'See the story behind your numbers',
    'cta_text' => 'In a 30-minute demo we show trends, plant comparisons and drill-downs on sample data shaped like your business.',
];
include __DIR__ . '/includes/templates/module.php';
