<?php
$page = [
    'path' => '/crm',
    'title' => 'CRM Software for Sales Teams | DotOne',
    'description' => 'Capture leads, manage the pipeline, schedule follow-ups and send quotations. DotOne CRM connects every deal to sales, stock and invoicing in one place.',
    'breadcrumbs' => [['Modules', '/modules'], ['CRM', '/crm']],
    'eyebrow' => 'ERP Module',
    'h1' => 'CRM Software for Sales Teams',
    'intro' => 'Manage leads, track opportunities, forecast revenue and keep sales in step with production. DotOne CRM is built for B2B and manufacturing sales, where pricing, approvals and delivery matter as much as closing the deal.',
    'highlights' => ['Lead pipeline', 'Follow-up reminders', 'Quotation approvals', 'Order to invoice'],
    'capabilities_heading' => 'From first enquiry to confirmed order',
    'capabilities_intro' => 'One CRM for leads, pipeline, quotations and follow-ups, linked to the rest of the ERP so a won deal moves straight into orders and invoicing.',
    'capabilities' => [
        ['users', 'Lead management', 'Bring leads from the website, WhatsApp, calls, distributors and field sales into one structured pipeline.'],
        ['trend', 'Pipeline and forecasting', 'Stage-based pipelines with deal value, probability and expected closing date, so revenue forecasts are based on real deals.'],
        ['doc', 'Quotations and pricing control', 'Create quotations linked to BOMs and pricing rules, with discount limits and approvals to protect margins.'],
        ['bell', 'Follow-up reminders', 'Reminders, emails, WhatsApp messages and tasks make sure no lead or opportunity is forgotten.'],
        ['flow', 'Order to invoice', 'Convert a confirmed deal into a sales order, production plan and invoice without re-entering anything.'],
        ['pin', 'Field sales activity', 'GPS-based visit logs and customer activity from salespeople on the road, in the same customer record.'],
    ],
    'workflow_intro' => 'Every deal follows the same path. DotOne records each step, so managers can see where a lead stands and what happens next.',
    'workflow' => [
        ['Capture', 'A lead arrives from the website, WhatsApp, a call, a distributor or a field visit.'],
        ['Qualify', 'The lead becomes an opportunity with a stage, deal value and expected closing date.'],
        ['Quote', 'A quotation is built from BOM-based pricing and sent for approval if the discount needs it.'],
        ['Follow up', 'Reminders and tasks keep the conversation moving until the customer decides.'],
        ['Convert', 'The won deal becomes a sales order, a production plan and an invoice.'],
    ],
    'reports' => [
        'Pipeline by stage and deal value',
        'Revenue forecast by probability and closing date',
        'Conversion ratios and funnel leakage',
        'Team-wise sales performance',
        'Field visit and customer activity logs',
        'Open quotations and pending approvals',
    ],
    'connected_intro' => 'CRM shares its data with sales, stock and accounts, so a confirmed deal becomes an order, a production plan and an invoice in the same system.',
    'connected' => ['sales-management', 'field-sales-tracking', 'production-management', 'inventory-management', 'accounting', 'reports-analytics'],
    'agent' => 'crm',
    'agent_questions' => [
        'Which leads have had no follow-up this week?',
        'Show deals expected to close this month.',
        'Which quotations are waiting for approval?',
    ],
    'faq' => [
        ['Is DotOne CRM suitable for manufacturing businesses?', 'Yes. It is built for long B2B sales cycles, BOM-based pricing and quotations, dealer and distributor sales, and multi-location sales teams.'],
        ['Can leads from WhatsApp and phone calls go into the CRM?', 'Yes. Leads from the website, WhatsApp, calls, distributors and field sales are collected in one pipeline.'],
        ['What happens when a deal is won?', 'The deal converts into a sales order and then an invoice, and can feed the production plan. See [Sales Management](/sales-management) for the order side.'],
        ['Can we track salespeople in the field?', 'Yes. GPS-based visit logs and activity tracking are available through [Field Sales Tracking](/field-sales-tracking), linked to the same customer records.'],
    ],
    'cta_heading' => 'See your sales pipeline in DotOne',
    'cta_text' => 'In a 30-minute demo we walk through lead capture, quotation approvals and the move from won deal to sales order.',
];
include __DIR__ . '/includes/templates/module.php';
