<?php
$page = [
    'path' => '/field-sales-tracking',
    'title' => 'Field Sales Tracking App | DotOne',
    'description' => 'Track field sales teams with GPS check-ins, visit logs, attendance and expenses. Android app with a live web dashboard for managers.',
    'breadcrumbs' => [['Modules', '/modules'], ['Field Sales Tracking', '/field-sales-tracking']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Field Sales Tracking App',
    'intro' => 'Know where your field team is, who they met and what they booked. Salespeople use the mobile app for attendance, visits, leads and expenses, and managers follow it all on a live web dashboard.',
    'highlights' => ['Live GPS tracking', 'Geo-fenced attendance', 'Visit and order logs', 'Expense claims'],
    'capabilities_heading' => 'Everything a field team does, in one app',
    'capabilities_intro' => 'The app records the working day as it happens, so managers do not have to wait for evening calls or spreadsheets.',
    'capabilities' => [
        ['pin', 'Live GPS tracking', 'See where each sales executive is, with route history and idle time.'],
        ['check', 'Geo-fenced attendance', 'Punch in and out only at approved offices, areas or customer sites.'],
        ['users', 'Visits and leads', 'Log customer visits, leads generated, orders booked and follow-ups from the phone.'],
        ['rupee', 'Expense claims', 'Record travel expenses and allowances, and send reimbursements for approval.'],
        ['chart', 'Manager dashboard', 'Team attendance, visits and sales numbers on a live web dashboard.'],
        ['phone', 'Offline and low-end phones', 'The app keeps working without signal and runs on low-end Android devices.'],
    ],
    'workflow_intro' => 'A field day follows the same pattern. DotOne captures each step from the phone, so the report writes itself.',
    'workflow' => [
        ['Plan the beat', 'Each executive gets a beat plan of customers and areas for the day.'],
        ['Punch in', 'Attendance is marked with a geo-fenced check-in at the start of the day.'],
        ['Visit', 'Each customer visit is checked in with location and time.'],
        ['Book', 'Orders, leads and follow-ups are recorded during the visit.'],
        ['Report', 'The daily activity report and expense claims go to the manager.'],
    ],
    'reports' => [
        'Daily activity report per executive',
        'Beat plans and visit summaries',
        'Route history and idle time',
        'Attendance and check-in log',
        'Visits to orders conversion',
        'Travel expense claims and approvals',
    ],
    'connected_intro' => 'Visits, leads and orders from the field go straight into CRM and sales, and attendance feeds HR.',
    'connected' => ['crm', 'sales-management', 'hrms', 'mobile-erp'],
    'agent' => 'sales',
    'agent_questions' => [
        'Which executives missed planned visits today?',
        'Show orders booked from field visits this week.',
        'Which customers have not been visited this month?',
    ],
    'faq' => [
        ['Which phones does the app run on?', 'The app runs on Android phones, including low-end devices. Managers use the web dashboard.'],
        ['Does it work without mobile signal?', 'Yes. Offline mode lets executives keep logging visits and orders, which sync when the phone is back online.'],
        ['Can field visits and orders go into our CRM?', 'Yes. Leads, visits and orders sync with [CRM](/crm) and [Sales Management](/sales-management), so there is no double entry.'],
        ['What kinds of teams use field sales tracking?', 'FMCG and distribution sales teams, pharma and medical reps, real estate, insurance agents and service sales teams.'],
    ],
    'cta_heading' => 'See your field team on one screen',
    'cta_text' => 'In a 30-minute demo we set up a sample beat and walk through check-ins, visits, orders and the manager dashboard.',
];
include __DIR__ . '/includes/templates/module.php';
