<?php
$page = [
    'path' => '/finance-management',
    'title' => 'Finance Management Software | DotOne',
    'description' => 'Finance management software for manufacturers. Track receivables, payables, cash flow, budgets and GST from live sales and purchase data in DotOne.',
    'breadcrumbs' => [['Modules', '/modules'], ['Finance Management', '/finance-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Finance Management Software',
    'intro' => 'See who owes you, who you owe and how much money you will have next week, without waiting for the books to close. DotOne builds the finance view from the sales and purchase records your teams already save.',
    'highlights' => ['Receivables ageing', 'Payables tracking', 'Cash flow view', 'GST summary'],
    'capabilities_heading' => 'A clear view of money, from daily operations',
    'capabilities_intro' => 'Finance management in DotOne works on live operational data. Your books stay in Tally through the Accounting and Tally Sync module; this one is for tracking and planning.',
    'capabilities' => [
        ['trend', 'Receivables', 'Outstanding amounts by customer and invoice, with ageing buckets built from your sales invoices and receipts.'],
        ['cart', 'Payables', 'What you owe each vendor and when it falls due, from purchase bills and payments.'],
        ['rupee', 'Cash flow and funds view', 'Money expected in and going out, built from open invoices, purchase bills and committed purchase orders.'],
        ['chart', 'Budgets vs actual', 'Set budgets by department or expense head and compare them with actual spend as it is recorded.'],
        ['doc', 'GST summary', 'Output and input GST by rate from your invoices and bills, ready to hand to your accountant.'],
        ['bell', 'Overdue alerts', 'Overdue customers and upcoming vendor payments are flagged, so follow-ups happen on time.'],
    ],
    'workflow_intro' => 'Finance numbers follow from the work your teams already do. Nobody has to compile them by hand.',
    'workflow' => [
        ['Sell and buy', 'Sales invoices and purchase bills are saved in their modules.'],
        ['Track', 'Receivables and payables update as invoices, receipts and payments are recorded.'],
        ['Plan', 'The cash flow view shows money due in and out over the coming weeks.'],
        ['Compare', 'Actual spend is compared with budget by department or expense head.'],
        ['Follow up', 'Overdue customers get reminders and vendor payments are scheduled.'],
    ],
    'reports' => [
        'Receivables ageing by customer',
        'Payables due by vendor',
        'Cash flow forecast by week',
        'Budget vs actual by department',
        'GST summary by rate',
        'Collections and payments register',
    ],
    'connected_intro' => 'Finance reads from sales, purchase and accounting, so the money view follows every order, bill and receipt.',
    'connected' => ['accounting', 'sales-management', 'purchase-management', 'reports-analytics'],
    'agent' => 'finance',
    'agent_questions' => [
        'Which customers are overdue by more than 60 days?',
        'What payments are due to vendors this week?',
        'How much cash do we expect to collect this month?',
    ],
    'faq' => [
        ['Does finance management replace Tally?', 'No. Your books, GST returns and final accounts stay in Tally. DotOne gives you the operational finance view and posts vouchers to Tally through [Accounting and Tally Sync](/accounting).'],
        ['Where does the cash flow view come from?', 'It is built from open sales invoices, purchase bills and committed purchase orders already in DotOne, so it reflects current operations.'],
        ['Can we track budgets?', 'Yes. You can set budgets by department or expense head and compare them with actual spend. We will set this up around how you plan today.'],
        ['Can overdue customers get reminders?', 'Yes. The Finance AI Agent flags overdue customers and drafts payment reminders for your team to review and send.'],
    ],
    'cta_heading' => 'See your money position in one place',
    'cta_text' => 'In a 30-minute demo we show receivables, payables and the cash flow view on sample data shaped like your business.',
];
include __DIR__ . '/includes/templates/module.php';
