<?php
$page = [
    'path' => '/hrms',
    'title' => 'HRMS Software for Indian Businesses | DotOne',
    'description' => 'Attendance, shifts, leave, onboarding and employee records in one HRMS built for Indian businesses, with biometric attendance and a mobile app for staff.',
    'breadcrumbs' => [['Modules', '/modules'], ['HRMS', '/hrms']],
    'eyebrow' => 'ERP Module',
    'h1' => 'HRMS Software',
    'intro' => 'Manage employee records, attendance, shifts, leave and onboarding in one system built for Indian businesses. HR teams and employees can start using it without long training.',
    'highlights' => ['Biometric attendance', 'Shifts and overtime', 'Leave and holidays', 'Employee self-service'],
    'capabilities_heading' => 'The whole employee lifecycle in one place',
    'capabilities_intro' => 'From hiring to appraisal, every HR record sits in one database, so attendance and leave flow straight into payroll.',
    'capabilities' => [
        ['id', 'Employee master', 'One employee database with personal and employment details, documents, policies, roles and departments.'],
        ['check', 'Attendance and biometric devices', 'Track daily attendance accurately, with biometric devices connected to the system.'],
        ['cog', 'Shifts and overtime', 'Set shift and overtime rules for each team, so work hours are counted the same way every month.'],
        ['bell', 'Leave and holidays', 'Configure leave policies and holiday calendars, with approvals routed to the right manager.'],
        ['users', 'Hiring and onboarding', 'Track candidates and interviews, issue offers and onboard new joiners with a structured handover.'],
        ['trend', 'Performance', 'Set goals and KPIs, run appraisal cycles and record manager feedback.'],
    ],
    'workflow_intro' => 'HR work follows the same cycle every month. DotOne keeps each step on record, so payroll starts from clean data.',
    'workflow' => [
        ['Onboard', 'A new joiner is added to the employee master with role, department and documents.'],
        ['Record attendance', 'Biometric punches and shift rules build each day\'s attendance and overtime.'],
        ['Approve leave', 'Leave requests go to the manager and update balances once approved.'],
        ['Review', 'Goals, KPIs and appraisal cycles track performance through the year.'],
        ['Hand to payroll', 'Approved attendance, overtime and leave go to payroll for the monthly run.'],
    ],
    'reports' => [
        'Daily attendance and overtime',
        'Leave balances and holiday calendar',
        'Headcount by department and role',
        'Statutory compliance reports',
        'Performance and appraisal reports',
        'HR dashboards for attendance and payroll',
    ],
    'connected_intro' => 'HRMS feeds attendance, leave and overtime to payroll, and shares employee records with the mobile app and field teams.',
    'connected' => ['payroll', 'mobile-erp', 'field-sales-tracking', 'reports-analytics'],
    'agent' => 'hr',
    'agent_questions' => [
        'Who was absent or late this week?',
        'Which leave requests clash in the same team?',
        'Show overtime hours by department this month.',
    ],
    'faq' => [
        ['What is the difference between HRMS and payroll software?', 'Payroll software handles pay runs and statutory compliance. An HRMS covers wider HR work as well: employee records, attendance, leave, onboarding and performance. DotOne has both, linked, with [Payroll](/payroll) as its own module.'],
        ['Does DotOne HRMS work with biometric devices?', 'Yes. Biometric attendance devices are connected during setup, so punches flow into daily attendance automatically.'],
        ['Can employees see their own attendance, leave and payslips?', 'Yes. Employees get self-service access to their attendance, leave, payslips and personal details.'],
        ['What does implementation involve?', 'We review your attendance, shift and leave policies, configure the system, migrate employee records, connect biometric devices and run a payroll dry run before go-live.'],
    ],
    'cta_heading' => 'See your HR processes in DotOne',
    'cta_text' => 'In a 30-minute demo we set up a sample of your shifts and leave rules and walk through attendance, approvals and the hand-off to payroll.',
];
include __DIR__ . '/includes/templates/module.php';
