<?php
$page = [
    'path' => '/inventory-management',
    'title' => 'Inventory Management Software | DotOne',
    'description' => 'Track stock across warehouses with batches, serial numbers, reorder levels, transfers and valuation. Real-time inventory reports in DotOne ERP.',
    'breadcrumbs' => [['Modules', '/modules'], ['Inventory Management', '/inventory-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Inventory Management Software',
    'intro' => 'Know what you have, where it is and what it is worth, across every store and warehouse. DotOne keeps stock accurate as goods are received, moved, consumed and dispatched, and warns you before you run short.',
    'highlights' => ['Multi-warehouse stock', 'QR scan-to-verify', 'Low-stock alerts', 'Real-time valuation'],
    'capabilities_heading' => 'Everything stock control needs, on one page',
    'capabilities_intro' => 'One inventory module covers the whole stock lifecycle, so you are not stitching together spreadsheets, registers and separate apps.',
    'capabilities' => [
        ['box', 'Multi-warehouse tracking', 'See stock by store, warehouse and location. Transfer between sites with a document trail on both sides.'],
        ['eye', 'QR scan-to-verify', 'Scan items on receipt, issue and dispatch so the system matches what is physically on the shelf.'],
        ['bell', 'Low-stock alerts and auto indents', 'Set reorder levels per item. When stock falls below them, DotOne raises a purchase indent automatically.'],
        ['doc', 'Smart GRN', 'Receive goods against the purchase order, record quantities and quality checks, and update stock in one step.'],
        ['rupee', 'Stock valuation', 'Real-time inventory value by item, category and warehouse, ready for month-end and audits.'],
        ['flow', 'Batches and serial numbers', 'Trace raw materials and finished goods by batch or serial number, from receipt to the customer.'],
    ],
    'workflow_intro' => 'Stock moves through the same steps in every business. DotOne records each one as it happens, so the numbers stay right without a separate reconciliation.',
    'workflow' => [
        ['Reorder', 'An item drops below its reorder level and an indent is raised for purchase.'],
        ['Receive', 'Goods arrive against the PO. The GRN updates stock and value.'],
        ['Store', 'Items are put away and tracked by warehouse, batch or serial number.'],
        ['Issue', 'Material is issued to production or transferred to another site.'],
        ['Dispatch', 'Finished goods leave against a sales order and stock updates instantly.'],
    ],
    'reports' => [
        'Current stock by item, warehouse and batch',
        'Items below reorder level',
        'Slow-moving and non-moving stock',
        'Stock ledger and movement history',
        'Inventory valuation by category and warehouse',
        'GRN and material issue registers',
    ],
    'connected_intro' => 'Inventory is shared with every other module, so a sales order, a job card or a purchase receipt changes stock the moment it is saved.',
    'connected' => ['purchase-management', 'sales-management', 'production-management', 'quality-management', 'accounting', 'reports-analytics'],
    'agent' => 'inventory',
    'agent_questions' => [
        'Which products are below reorder level?',
        'Show slow-moving stock in the main warehouse.',
        'Which warehouse has excess stock of this item?',
    ],
    'faq' => [
        ['Can DotOne manage stock across more than one warehouse?', 'Yes. Stock is tracked separately for each store and warehouse, with transfers between them recorded on both sides.'],
        ['How do low-stock alerts work?', 'You set a reorder level for each item. When available stock falls below it, DotOne alerts the right people and can raise a purchase indent automatically.'],
        ['Does inventory sync with Tally?', 'Yes. Stock and vouchers can sync with Tally Prime or Tally ERP 9 through the DotOne Tally connector.'],
        ['Can we track items by batch or serial number?', 'Yes. Batch and serial tracking let you trace an item from goods receipt through production to the customer.'],
    ],
    'cta_heading' => 'See your stock the way DotOne would show it',
    'cta_text' => 'In a 30-minute demo we set up a sample of your items and warehouses and walk through receipt, transfer and reorder.',
];
include __DIR__ . '/includes/templates/module.php';
