<?php
$page = [
    'path' => '/manufacturing-erp',
    'title' => 'Manufacturing ERP Software for Indian Manufacturers | DotOne',
    'description' => 'ERP for manufacturers: BOM, production planning, job cards, inventory, quality and dispatch connected, with AI agents that flag delays and shortages.',
    'breadcrumbs' => [['Modules', '/modules'], ['Manufacturing ERP', '/manufacturing-erp']],
    'eyebrow' => 'ERP for Factories',
    'h1' => 'Manufacturing ERP Software',
    'intro' => 'One ERP for the whole plant: production, inventory, planning, quality, purchase, sales and finance. Replace spreadsheets and disconnected systems, and run the factory from order to dispatch in one place.',
    'highlights' => ['Production planning', 'Inventory control', 'Quality tracking', 'Real-time reporting'],
    'capabilities_heading' => 'The core modules a factory runs on',
    'capabilities_intro' => 'Each part of the plant works in its own module, and all of them share the same data, so a job card, a GRN or an invoice updates everything it touches.',
    'capabilities' => [
        ['factory', 'Production management', 'Work orders, BOM, routing, scheduling, WIP tracking and production output.'],
        ['box', 'Inventory and stores', 'Raw material, semi-finished and finished goods, with batch tracking and stock valuation.'],
        ['shield', 'Quality management', 'Quality checks, defect tracking and rejection analysis, with camera-based inspection through Vision AI.'],
        ['cart', 'Purchase and vendors', 'RFQs, purchase orders, GRN, supplier performance and cost control.'],
        ['truck', 'Sales and dispatch', 'Orders, invoicing, dispatch planning and customer tracking.'],
        ['chart', 'Reports and analytics', 'Live dashboards, KPIs, OEE and productivity for management.'],
    ],
    'workflow_intro' => 'A sales order drives the work. Material is checked before production starts, and stock updates on its own as goods move through the plant.',
    'workflow' => [
        ['Sales order', 'The customer order is entered and becomes the plan for production.'],
        ['BOM and material', 'Material is checked against the BOM and reserved from stock, so shortages show up early.'],
        ['Job cards', 'Job cards go to the floor, and progress is recorded as the work happens.'],
        ['Quality check', 'Inspections are recorded in process and before dispatch.'],
        ['Dispatch and invoice', 'Finished goods move to dispatch and a GST invoice, with stock updated automatically.'],
    ],
    'reports' => [
        'Production output and WIP by job',
        'OEE and productivity by machine',
        'Rejection and defect analysis',
        'Stock of raw material, WIP and finished goods',
        'Supplier performance and purchase cost',
        'Dispatch plan and invoices',
    ],
    'connected_intro' => 'Manufacturing ERP is not a separate product. It is these DotOne modules working on the same data.',
    'connected' => ['production-management', 'inventory-management', 'quality-management', 'purchase-management', 'sales-management', 'reports-analytics'],
    'agent' => 'production',
    'agent_questions' => [
        'Which job cards are running late this week?',
        'Is material ready for the jobs planned on Monday?',
        'What was OEE on each machine yesterday?',
    ],
    'faq' => [
        ['What is manufacturing ERP?', 'A central system that helps a factory plan, run and monitor production. Planning, inventory, quality, purchase, sales and finance all work from the same records. Read our guide: [What is ERP?](/guides/what-is-erp)'],
        ['Can DotOne connect to machines and cameras?', 'Yes. DotOne can take in machine data and connect to CCTV cameras and IoT systems, so output, downtime and quality checks are recorded from the floor. See [Vision AI](/vision-ai).'],
        ['How is manufacturing ERP rolled out?', 'In four stages: we map your workflows and reporting needs, configure BOM, production, inventory and user roles, migrate master data and connect shop-floor systems, then go live with training and ongoing support.'],
        ['How is our factory data protected?', 'Data is encrypted in transit and at rest, access is role-based with audit logs, and backups are automated. See our [security practices](/security).'],
    ],
    'cta_heading' => 'Run your factory on one ERP',
    'cta_text' => 'Book a demo and we will walk one of your products from sales order to job card, quality check and dispatch.',
];
include __DIR__ . '/includes/templates/module.php';
