<?php
$page = [
    'path' => '/mobile-erp',
    'title' => 'Mobile ERP App for Field and Shop Floor | DotOne',
    'description' => 'Mobile ERP app for Indian businesses. Mark attendance, log field sales visits and orders, approve requests and check dashboards from your phone.',
    'breadcrumbs' => [['Modules', '/modules'], ['Mobile ERP', '/mobile-erp']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Mobile ERP App',
    'intro' => 'Not everyone who works in your business sits at a desk. The DotOne mobile app lets staff mark attendance, field teams record visits and orders, and managers approve requests and check numbers from their phone.',
    'highlights' => ['Mobile attendance', 'Field sales check-ins', 'Approvals on the go', 'Dashboards'],
    'capabilities_heading' => 'The ERP in your pocket',
    'capabilities_intro' => 'The mobile app works on the same data as the web system, so what is recorded on the phone is available to every team straight away.',
    'capabilities' => [
        ['id', 'Attendance', 'Staff mark attendance from their phone, with geo-fencing where you need it. It flows into HRMS and payroll.'],
        ['pin', 'Field sales check-ins', 'Sales staff check in at customer locations with GPS and log the visit.'],
        ['cart', 'Orders from the field', 'Record a customer order during the visit, so it reaches the sales team without re-typing.'],
        ['check', 'Approvals', 'Managers approve purchase orders, quotations, leave and other requests from the phone.'],
        ['chart', 'Dashboards', 'Check sales, stock and other key numbers while away from the office.'],
        ['bell', 'Notifications', 'Get alerts for pending approvals and tasks that need your attention.'],
    ],
    'workflow_intro' => 'A typical day for a field salesperson using the DotOne app.',
    'workflow' => [
        ['Start the day', 'Mark attendance from the phone at the start of the shift.'],
        ['Visit', 'Check in at the customer location with GPS.'],
        ['Take the order', 'Record the order and notes during the visit.'],
        ['Approve', 'The manager approves the order or discount from their phone.'],
        ['Review', 'The manager sees visits and orders on the dashboard.'],
    ],
    'reports' => [
        'Attendance by employee and location',
        'Field visits by salesperson',
        'Orders taken in the field',
        'Pending approvals by manager',
        'Daily activity summary',
        'Sales dashboard on mobile',
    ],
    'connected_intro' => 'The app is a window into the same DotOne modules, so attendance, visits and orders reach HR, sales and reports as soon as they are saved.',
    'connected' => ['hrms', 'field-sales-tracking', 'sales-management', 'reports-analytics'],
    'agent' => null,
    'faq' => [
        ['Which phones does the app work on?', 'Field sales, attendance and approvals work on Android, with full control from the web dashboard. Ask us about other devices during the demo.'],
        ['Is mobile attendance linked to payroll?', 'Yes. Attendance marked on the app flows into [HRMS](/hrms) and then into [payroll](/payroll).'],
        ['Can managers approve from the phone?', 'Yes. Pending approvals appear on the app, so managers can approve or reject without logging into the web system.'],
        ['How does field sales tracking work?', 'Salespeople check in at customer locations with GPS and log visits and orders. See [field sales tracking](/field-sales-tracking) for more.'],
    ],
    'cta_heading' => 'See DotOne on your phone',
    'cta_text' => 'In a 30-minute demo we show attendance, a field visit, an order and an approval on the mobile app.',
];
include __DIR__ . '/includes/templates/module.php';
