<?php
$page = [
    'path' => '/payroll',
    'title' => 'Payroll Software with PF, ESI and TDS | DotOne',
    'description' => 'Run payroll with PF, ESI, PT and TDS worked out, generate payslips in one run and sync salaries with attendance and accounts. Built for Indian businesses.',
    'breadcrumbs' => [['Modules', '/modules'], ['Payroll', '/payroll']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Payroll Software',
    'intro' => 'Pay employees accurately and on time, with Indian statutory deductions worked out for you. DotOne calculates salaries from attendance, applies PF, ESIC, PT and TDS, and produces payslips and registers in one run.',
    'highlights' => ['PF, ESIC, PT and TDS', 'Payslips in one run', 'Salary from attendance', 'Payroll registers'],
    'capabilities_heading' => 'Payroll built for Indian rules',
    'capabilities_intro' => 'Replace spreadsheets and manual calculations with one payroll that reads attendance and writes to accounts.',
    'capabilities' => [
        ['rupee', 'Salary processing', 'Salaries are calculated from attendance, overtime, incentives and deductions.'],
        ['shield', 'Statutory compliance', 'PF, ESIC, Professional Tax and TDS rules are built in, with reports for filing.'],
        ['doc', 'Payslips and registers', 'Generate payslips, payroll registers and compliance reports for all employees in one run.'],
        ['cog', 'Salary structures and pay cycles', 'Set up complex salary structures, components and pay cycles to match your policies.'],
        ['pin', 'Multiple states', 'Handle employees across states, with the labour law and Professional Tax rules that apply to each.'],
        ['link', 'Attendance and accounts sync', 'Attendance comes in from HRMS and salary entries go to accounts, with no re-keying.'],
    ],
    'workflow_intro' => 'The monthly run follows the same steps every time. DotOne does the calculations, so HR only checks and approves.',
    'workflow' => [
        ['Close attendance', 'Attendance, overtime and leave for the month are finalised in HRMS.'],
        ['Calculate', 'Gross salary is worked out from the salary structure, attendance, overtime and incentives.'],
        ['Deduct', 'PF, ESIC, PT, TDS and other deductions are applied automatically.'],
        ['Issue payslips', 'Payslips and the payroll register are generated for the whole company in one run.'],
        ['Post to accounts', 'Salary entries sync to accounts, ready for payment and filing.'],
    ],
    'reports' => [
        'Monthly payroll register',
        'PF and ESIC reports',
        'Professional Tax and TDS reports',
        'Employee payslips',
        'Attendance and overtime used for salary',
        'Deductions and benefits by employee',
    ],
    'connected_intro' => 'Payroll reads attendance and leave from HRMS and posts salary entries to accounts, so the numbers match across departments.',
    'connected' => ['hrms', 'accounting', 'finance-management', 'reports-analytics'],
    'agent' => 'hr',
    'agent_questions' => [
        'Whose attendance is incomplete before this month\'s run?',
        'Show overtime to be paid this month by department.',
        'Which employees\' net pay changed from last month?',
    ],
    'faq' => [
        ['Which statutory deductions does DotOne Payroll handle?', 'PF, ESIC, Professional Tax and TDS are built in, along with the reports you need for compliance.'],
        ['Is salary linked to attendance?', 'Yes. Salary is calculated from attendance, overtime and leave recorded in [HRMS](/hrms), so there is no separate data entry.'],
        ['How is payroll software different from an HRMS?', 'Payroll focuses on salary processing, tax deductions, payslips and statutory compliance. An HRMS manages the wider employee lifecycle, including attendance, leave and performance. In DotOne they work together.'],
        ['Who is DotOne Payroll for?', 'Small and medium businesses moving off spreadsheets, manufacturing companies with shifts, overtime and large workforces, and growing teams that want to scale payroll without adding HR overhead.'],
    ],
    'cta_heading' => 'See a payroll run in DotOne',
    'cta_text' => 'In a 30-minute demo we run a sample month of payroll, from attendance to payslips and statutory reports.',
];
include __DIR__ . '/includes/templates/module.php';
