<?php
$page = [
    'path' => '/production-management',
    'title' => 'Production Management Software | DotOne',
    'description' => 'Plan production, manage multi-level BOMs and job cards, track WIP and monitor line output and OEE in real time.',
    'breadcrumbs' => [['Modules', '/modules'], ['Production Management', '/production-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Production Management Software',
    'intro' => 'Plan production and watch it happen. DotOne tracks output, downtime and efficiency across machines, lines and plants, so supervisors and plant heads see problems while there is still time to act.',
    'highlights' => ['Multi-level BOMs', 'Job cards and WIP', 'Machine status', 'Live OEE'],
    'capabilities_heading' => 'Planning and shopfloor tracking in one module',
    'capabilities_intro' => 'Production plans, job cards and machine data sit in the same system, so target and actual are always compared on the same numbers.',
    'capabilities' => [
        ['flow', 'Planning, BOMs and job cards', 'Plan production with multi-level BOMs, issue job cards and track work in progress at each stage.'],
        ['chart', 'Live dashboards', 'Production count, target versus actual, efficiency and machine status on one screen.'],
        ['cog', 'Machine status', 'See which machines are running, idle, broken down or under maintenance.'],
        ['eye', 'Downtime analysis', 'Record downtime reasons and find the losses and bottlenecks behind them.'],
        ['users', 'Shift and operator tracking', 'Track output by shift, operator, line and department.'],
        ['bell', 'OEE and alerts', 'Calculate availability, performance, quality and OEE, with alerts for downtime, low output and delays.'],
    ],
    'workflow_intro' => 'Each job moves from plan to finished output. DotOne records every step, so delays show up while the shift is still running.',
    'workflow' => [
        ['Plan', 'Production is planned against orders, using the multi-level BOM for each product.'],
        ['Release', 'Job cards are issued to lines and machines with targets for the shift.'],
        ['Run', 'Output, cycle time and machine status are tracked as work progresses.'],
        ['Record losses', 'Downtime and its reasons are logged, and alerts go out when output falls behind.'],
        ['Review', 'Shift, operator and OEE reports show what went well and where time was lost.'],
    ],
    'reports' => [
        'Target versus actual output by line and shift',
        'Downtime by reason and machine',
        'OEE by machine, line and plant',
        'Shift-wise and operator reports',
        'Machine utilisation and cycle time',
        'Work in progress by job card',
    ],
    'connected_intro' => 'Production shares data with stock and quality, so material, output and inspection results stay in one record.',
    'connected' => ['inventory-management', 'quality-management', 'reports-analytics'],
    'agent' => 'production',
    'agent_questions' => [
        'Which machines had the most downtime this week?',
        'Show target versus actual output for today\'s shifts.',
        'Which job cards are running behind plan?',
    ],
    'faq' => [
        ['How does DotOne calculate OEE?', 'OEE is calculated from availability, performance and quality for each machine and line, using the output and downtime recorded on the shopfloor.'],
        ['Can DotOne connect to our machines?', 'Yes. Machines, PLCs and IoT sensors can be connected so output and machine status are captured without manual entry.'],
        ['Does it work for more than one plant?', 'Yes. You can start with a single plant and extend monitoring to several factories, with reports for each site and the whole business.'],
        ['Can quality inspection data be linked to production?', 'Yes. Inspection results, including [Vision AI](/vision-ai) checks, can sit alongside production data. See [Quality Management](/quality-management).'],
    ],
    'cta_heading' => 'See your shopfloor in DotOne',
    'cta_text' => 'In a 30-minute demo we set up a sample line and walk through job cards, machine status, downtime and OEE.',
];
include __DIR__ . '/includes/templates/module.php';
