<?php
$page = [
    'path' => '/purchase-management',
    'title' => 'Purchase Management Software | DotOne',
    'description' => 'Purchase management software for manufacturers. Raise RFQs, compare vendor quotes, auto-generate purchase orders with approvals and sync to Tally.',
    'breadcrumbs' => [['Modules', '/modules'], ['Purchase Management', '/purchase-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Purchase Management Software',
    'intro' => 'Buy the right material, from the right vendor, at the right time. DotOne takes a purchase from indent to RFQ, vendor comparison, approved PO and goods receipt, with every step on record.',
    'highlights' => ['RFQ and vendor comparison', 'Auto PO with approvals', 'PO-linked goods receipt', 'Tally sync'],
    'capabilities_heading' => 'Procurement software that follows how you buy',
    'capabilities_intro' => 'Most purchase delays come from quotes lost in email and POs waiting for a signature. The purchase module keeps quotes, approvals and receipts in one place.',
    'capabilities' => [
        ['doc', 'RFQ software', 'Send requests for quotation to several vendors for the same requirement and collect their replies against it.'],
        ['chart', 'Side-by-side vendor comparison', 'Compare vendor quotes on price and terms with past purchase history in view before you decide.'],
        ['cart', 'Purchase order software', 'Generate the PO from the chosen quote or from an indent. It is routed for approval before it goes to the vendor.'],
        ['bell', 'Indents from low stock', 'When an item falls below its reorder level, inventory raises a purchase indent, so buying starts on time.'],
        ['box', 'Goods receipt against the PO', 'Receive material against the PO with Smart GRN, record quantities and quality checks, and update stock in one step.'],
        ['rupee', 'Funds and Tally sync', 'See what is committed to vendors, and push purchase invoices and debit notes to Tally without re-entry.'],
    ],
    'workflow_intro' => 'A purchase passes through the same five steps every time. DotOne connects them, so a PO always traces back to a need and forward to a receipt.',
    'workflow' => [
        ['Indent', 'A store or department raises a requirement, or a low-stock alert raises it automatically.'],
        ['RFQ', 'Requests for quotation go to the vendors you choose for that item.'],
        ['Compare', 'Quotes are compared side by side and the best vendor is selected.'],
        ['Approve', 'The PO is generated and routed for approval before it is sent.'],
        ['Receive', 'Goods arrive against the PO. The GRN updates stock and the bill can sync to Tally.'],
    ],
    'reports' => [
        'Pending indents and open purchase orders',
        'RFQ and quote comparison history',
        'Purchases by vendor, item and period',
        'POs awaiting approval',
        'Pending deliveries against POs',
        'GRN and purchase invoice registers',
    ],
    'connected_intro' => 'Purchase takes demand from inventory and production, and hands receipts to stores, quality checks and accounts.',
    'connected' => ['inventory-management', 'production-management', 'quality-management', 'accounting', 'reports-analytics'],
    'agent' => null,
    'agent_questions' => [],
    'faq' => [
        ['Can DotOne compare quotes from several vendors?', 'Yes. You raise one RFQ to multiple vendors and see their quotes side by side, with past purchase history for context.'],
        ['How do purchase approvals work?', 'Purchase orders are routed through an approval workflow you set up. A PO is sent to the vendor only after it is approved.'],
        ['Can purchases start automatically when stock is low?', 'Yes. Set a reorder level per item. When stock falls below it, DotOne raises a purchase indent so the buying team can act.'],
        ['Do purchase bills sync with Tally?', 'Yes. Purchase invoices and debit notes can sync to Tally Prime or Tally ERP 9 through the DotOne Tally connector.'],
    ],
    'cta_heading' => 'See your purchase cycle in DotOne',
    'cta_text' => 'In a 30-minute demo we run one of your regular purchases through indent, RFQ, comparison, approval and goods receipt.',
];
include __DIR__ . '/includes/templates/module.php';
