<?php
$page = [
    'path' => '/quality-management',
    'title' => 'Quality Management Software | DotOne',
    'description' => 'Quality management software for manufacturers. Inspections at receipt and on the line, rejection logging, rework tracking and batch traceability.',
    'breadcrumbs' => [['Modules', '/modules'], ['Quality Management', '/quality-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Quality Management Software',
    'intro' => 'Catch defects early and know why they happened. DotOne records inspections, rejections and rework against the same job cards, batches and receipts your team already uses, so quality data is never a separate register.',
    'highlights' => ['Inspection at GRN and on the line', 'Rejection logging', 'Rework tracking', 'Batch traceability'],
    'capabilities_heading' => 'Quality control software tied to production',
    'capabilities_intro' => 'Quality records are only useful when they link to the material, the job and the batch. The quality module keeps those links for you.',
    'capabilities' => [
        ['box', 'Incoming inspection', 'Record quality checks when material is received against a PO, before it is accepted into stock.'],
        ['factory', 'In-process checks', 'Log inspections against job cards at each stage, so problems are found before the next operation.'],
        ['shield', 'Rejection logging', 'Record rejected quantities with a reason, by job, machine, shift and item.'],
        ['flow', 'Rework workflows', 'Send rejected items for rework with a clear trail of what was done and what passed after.'],
        ['eye', 'Vision AI checks', 'Plants using DotOne Vision AI can add camera-based inline inspection on existing CCTV, with defects logged in the same records.'],
        ['doc', 'Batch traceability', 'Trace a finished batch back to the raw material batch and the jobs it went through.'],
    ],
    'workflow_intro' => 'Quality is checked at every point where material changes hands. DotOne records each check where it happens.',
    'workflow' => [
        ['Receive', 'Incoming material is inspected at goods receipt before it goes into stock.'],
        ['Inspect', 'Checks are logged against the job card at each production stage.'],
        ['Reject', 'Failed items are logged with quantity and reason.'],
        ['Rework', 'Items go for rework and are inspected again before they move on.'],
        ['Release', 'Passed goods move to finished stock with their batch history intact.'],
    ],
    'reports' => [
        'Rejection by item, reason and stage',
        'Rejection by machine, shift and operator',
        'Incoming inspection results by vendor',
        'Rework register and status',
        'Batch traceability report',
        'Quality trend over time',
    ],
    'connected_intro' => 'Quality reads from purchase receipts and production job cards, and its results flow into stock and reports.',
    'connected' => ['production-management', 'purchase-management', 'inventory-management', 'reports-analytics'],
    'agent' => null,
    'agent_questions' => [],
    'faq' => [
        ['Can we inspect material when it arrives?', 'Yes. Quality checks are recorded as part of the goods receipt against the PO, so rejected material does not enter usable stock.'],
        ['How is rejection data captured?', 'Supervisors log rejected quantities with a reason against the job card. Reports then show rejection by item, stage, machine and shift.'],
        ['Does it work with Vision AI inspection?', 'Yes. If you use DotOne Vision AI for inline inspection on your cameras, detected defects feed the same quality records. See [AI quality inspection](/vision-ai/quality-inspection) for details.'],
        ['Can we trace a defect back to the raw material?', 'Yes. Batch tracking links finished goods to the jobs and raw material batches used, so you can trace a complaint to its source.'],
    ],
    'cta_heading' => 'See your quality checks in DotOne',
    'cta_text' => 'In a 30-minute demo we set up a sample item with incoming and in-process checks and walk through rejection and rework.',
];
include __DIR__ . '/includes/templates/module.php';
