<?php
$page = [
    'path' => '/reports-analytics',
    'title' => 'Business Reporting Software | DotOne',
    'description' => 'Business reporting software for manufacturers. Live dashboards, MIS reports and multi-plant reporting from sales, stock, production and purchase data.',
    'breadcrumbs' => [['Modules', '/modules'], ['Reports and Analytics', '/reports-analytics']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Business Reports and Analytics',
    'intro' => 'Get the numbers you need without waiting for someone to build a spreadsheet. DotOne reports read straight from the same records your teams work in, so sales, stock, production and purchase figures are current when you open them.',
    'highlights' => ['Live dashboards', 'MIS reports', 'Multi-plant view', 'Role-based access'],
    'capabilities_heading' => 'ERP reports from one set of data',
    'capabilities_intro' => 'When every module shares one database, reports do not need to be stitched together. You see the whole business, or one plant, from the same place.',
    'capabilities' => [
        ['chart', 'Live dashboards', 'Dashboards for sales, stock, production and purchase that update as transactions are saved.'],
        ['doc', 'MIS reports', 'Standard management reports for owners and department heads, ready without manual compilation.'],
        ['factory', 'Multi-plant reporting', 'Centralised reporting across plants and warehouses, with the option to drill into one site.'],
        ['cog', 'Production and OEE', 'Target versus actual output, downtime and OEE from the shopfloor, next to the commercial numbers.'],
        ['trend', 'Sales and forecast', 'Revenue, pipeline and forecast dashboards built from CRM and sales data.'],
        ['shield', 'Role-based access', 'People see the reports their role allows, so plant, sales and accounts data stay with the right teams.'],
    ],
    'workflow_intro' => 'Reports are not a separate project in DotOne. They follow from the work your teams already record.',
    'workflow' => [
        ['Record', 'Teams save orders, receipts, job cards and invoices in their modules.'],
        ['Combine', 'Every module writes to the same data, so nothing needs to be merged.'],
        ['View', 'Dashboards and MIS reports show the current position by plant, team or period.'],
        ['Drill down', 'Open a total to see the orders, items or jobs behind it.'],
        ['Act', 'Managers follow up on the exceptions the reports show.'],
    ],
    'reports' => [
        'Sales, orders and revenue by period',
        'Stock position and valuation',
        'Production output, downtime and OEE',
        'Purchase and vendor summary',
        'Receivables and payables summary',
        'Plant-wise MIS for management',
    ],
    'connected_intro' => 'Reports and Analytics reads from every module, so a single dashboard can show sales, stock, production and money together.',
    'connected' => ['sales-management', 'inventory-management', 'production-management', 'purchase-management', 'accounting', 'hrms'],
    'agent' => 'reporting',
    'agent_questions' => [
        'What were our top ten customers by sales last month?',
        'Compare production output between our two plants this week.',
        'Which items have the highest stock value right now?',
    ],
    'faq' => [
        ['What reports come with DotOne?', 'Each module comes with its own standard reports, and Reports and Analytics brings them together in dashboards and MIS reports for management.'],
        ['Can we see all our plants in one place?', 'Yes. Reporting is centralised across plants and warehouses, and you can filter to one site when you need to.'],
        ['Are the numbers live?', 'Yes. Reports read from the same records your teams save in DotOne, so they reflect the latest transactions.'],
        ['Can we control who sees which reports?', 'Yes. Role-based access means each person sees only the data relevant to their role.'],
    ],
    'cta_heading' => 'See your business on one dashboard',
    'cta_text' => 'In a 30-minute demo we show live dashboards and MIS reports built on sample data shaped like your business.',
];
include __DIR__ . '/includes/templates/module.php';
