<?php
$page = [
    'path' => '/sales-management',
    'title' => 'Sales Management Software | DotOne',
    'description' => 'Sales management software for manufacturers. Quotations with approvals, sales orders, GST invoices and dispatch in one flow, synced to Tally.',
    'breadcrumbs' => [['Modules', '/modules'], ['Sales Management', '/sales-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Sales Management Software',
    'intro' => 'Run every order from quotation to invoice in one place. DotOne links the quote, the sales order, the stock, the dispatch and the GST invoice, so your team stops re-typing the same order into three systems.',
    'highlights' => ['Quotation to invoice in one flow', 'Approval and discount rules', 'GST invoices synced to Tally', 'Customer portal'],
    'capabilities_heading' => 'Sales order management built for manufacturers',
    'capabilities_intro' => 'Manufacturing sales has BOM-based pricing, approvals and delivery dates that depend on the shopfloor. The sales module keeps all of it on one order.',
    'capabilities' => [
        ['doc', 'Quotation software with controls', 'Build quotations from your item and BOM pricing. Discount limits and approval rules protect your margin before a quote goes out.'],
        ['flow', 'Order to invoice', 'Convert an accepted quotation into a sales order, then into a GST invoice, without keying the details again.'],
        ['box', 'Stock and production linkage', 'A confirmed order checks available stock and can feed a production plan when goods need to be made.'],
        ['truck', 'Dispatch and delivery challans', 'Plan dispatch against the order, generate delivery challans and record proof of delivery.'],
        ['users', 'Customer portal', 'Customers can view their quotations and orders through a self-service portal, so fewer calls come to your team.'],
        ['trend', 'Sales tracking software', 'Follow every order by status, customer and salesperson, with revenue and forecast dashboards for management.'],
    ],
    'workflow_intro' => 'The same order moves from your sales desk to the shopfloor to the accounts team. DotOne records each step on one document trail.',
    'workflow' => [
        ['Quote', 'Prepare a quotation with pricing rules. It goes for approval if the discount is above the limit.'],
        ['Confirm', 'The customer accepts and the quote becomes a sales order with delivery dates.'],
        ['Fulfil', 'Stock is reserved, or a production plan is raised for items that need to be made.'],
        ['Dispatch', 'Goods leave with a delivery challan and stock updates on dispatch.'],
        ['Invoice', 'The GST invoice is raised from the order and can sync to Tally as a sales voucher.'],
    ],
    'reports' => [
        'Quotation register with status and value',
        'Open sales orders and pending dispatch',
        'Sales by customer, item and salesperson',
        'Order to invoice conversion',
        'Sales forecast and revenue trend',
        'Invoice and credit note registers',
    ],
    'connected_intro' => 'Sales reads stock from inventory, sends demand to production and passes invoices to accounting, so one order updates every team at once.',
    'connected' => ['crm', 'inventory-management', 'production-management', 'accounting', 'field-sales-tracking', 'reports-analytics'],
    'agent' => 'sales',
    'agent_questions' => [
        'Which quotations from last week have no follow-up yet?',
        'Show open orders due for dispatch this week.',
        'Which customers ordered less this quarter than last?',
    ],
    'faq' => [
        ['What is the difference between CRM and sales management in DotOne?', 'CRM handles leads, follow-ups and the pipeline before a deal is won. Sales management takes over from the quotation and runs the order through stock, dispatch and invoicing. Both share the same customer records.'],
        ['Can quotations need approval before they are sent?', 'Yes. You set discount limits and approval rules. A quotation outside those limits goes to the right person for approval before it reaches the customer.'],
        ['Do sales invoices go to Tally?', 'Yes. Sales invoices and credit notes can sync to Tally Prime or Tally ERP 9 with the GST breakup, through the DotOne Tally connector.'],
        ['Can a sales order trigger production?', 'Yes. When an order needs goods that are not in stock, it can feed the production plan, so the shopfloor works to confirmed orders.'],
    ],
    'cta_heading' => 'See one order go from quote to invoice',
    'cta_text' => 'In a 30-minute demo we take a sample order from your business through quotation, approval, dispatch and GST invoice.',
];
include __DIR__ . '/includes/templates/module.php';
