<?php
$page = [
    'path' => '/warehouse-management',
    'title' => 'Warehouse Management Software | DotOne',
    'description' => 'Warehouse management software for manufacturers. Inward with GRN, storage locations, picking, packing, dispatch and transfers across every warehouse.',
    'breadcrumbs' => [['Modules', '/modules'], ['Warehouse Management', '/warehouse-management']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Warehouse Management Software',
    'intro' => 'Run every warehouse from goods inward to dispatch. DotOne records what arrives, where it is stored, what is picked and what leaves, so the stock in the system matches what is on the racks.',
    'highlights' => ['GRN against PO', 'Storage locations', 'Pick and pack', 'Multi-warehouse'],
    'capabilities_heading' => 'From the gate to the dispatch bay',
    'capabilities_intro' => 'Warehouse work is a chain of small steps. When each one is recorded as it happens, nobody has to hunt for stock or reconcile registers at month-end.',
    'capabilities' => [
        ['doc', 'Inward and GRN', 'Receive material against the purchase order, record quantities and quality checks, and update stock in one step.'],
        ['pin', 'Put-away and storage locations', 'Assign received goods to a rack, bin or area, so the team knows where each item and batch is kept.'],
        ['box', 'Picking and packing', 'Pick material against a sales order or issue request, then pack and mark it ready for dispatch.'],
        ['truck', 'Outward and dispatch', 'Dispatch against the sales order with a delivery challan. Stock reduces the moment goods leave.'],
        ['flow', 'Transfers between sites', 'Move stock between warehouses and plants with a document on both sides, so nothing is lost in transit.'],
        ['eye', 'QR scan-to-verify', 'Scan items on receipt, put-away, picking and dispatch, so the system matches what is physically on the shelf.'],
    ],
    'workflow_intro' => 'Every warehouse follows the same basic flow. DotOne records each step, so the stock position is right at any time of day.',
    'workflow' => [
        ['Inward', 'Material arrives at the gate and is received against the PO with a GRN.'],
        ['Put away', 'Goods are placed in a storage location and the location is recorded.'],
        ['Pick', 'The team picks items for a sales order, production issue or transfer.'],
        ['Pack', 'Picked goods are packed and marked ready for dispatch.'],
        ['Outward', 'Goods leave with a delivery challan and stock updates straight away.'],
    ],
    'reports' => [
        'Stock by warehouse and storage location',
        'GRN and inward register',
        'Pending picks and dispatches',
        'Outward and delivery challan register',
        'Inter-warehouse transfers in transit',
        'Stock movement history by item and batch',
    ],
    'connected_intro' => 'The warehouse sits between buying and selling. Purchase orders feed inward, sales orders feed picking, and every movement updates inventory and reports.',
    'connected' => ['inventory-management', 'purchase-management', 'sales-management', 'reports-analytics'],
    'agent' => 'inventory',
    'agent_questions' => [
        'Which GRNs are still pending put-away?',
        'What is waiting to be dispatched from the main warehouse today?',
        'Which warehouse has excess stock of HDPE granules?',
    ],
    'faq' => [
        ['What is the difference between inventory and warehouse management in DotOne?', '[Inventory management](/inventory-management) tracks how much stock you have, its value and reorder levels. Warehouse management covers the physical work: receiving, storing, picking, packing and dispatch.'],
        ['Can we manage more than one warehouse?', 'Yes. Each warehouse and plant has its own stock, and transfers between them are recorded on both sides.'],
        ['Can we track where items are stored?', 'Yes. You can record the storage location for received goods, so the team knows where to find each item when it is needed.'],
        ['Is goods receipt linked to purchase orders?', 'Yes. Goods are received against the PO with a GRN, which records quantity and quality checks and updates stock. See [purchase management](/purchase-management).'],
    ],
    'cta_heading' => 'See your warehouse flow in DotOne',
    'cta_text' => 'In a 30-minute demo we walk one shipment from inward and put-away to picking and dispatch, using items like yours.',
];
include __DIR__ . '/includes/templates/module.php';
