<?php
$page = [
    'path' => '/workflow-automation',
    'title' => 'Workflow Automation Software | DotOne',
    'description' => 'Workflow automation for manufacturers. Approval chains, alerts, automatic indents, hand-offs between departments and escalations inside DotOne ERP.',
    'breadcrumbs' => [['Modules', '/modules'], ['Workflow Automation', '/workflow-automation']],
    'eyebrow' => 'ERP Module',
    'h1' => 'Workflow Automation Software',
    'intro' => 'Most delays are not in the work itself but in the wait between steps: a PO waiting for a signature, an indent nobody raised, a dispatch the accounts team did not hear about. DotOne moves work to the next person as soon as a step is done.',
    'highlights' => ['Approval chains', 'Alerts', 'Auto indents', 'Escalations'],
    'capabilities_heading' => 'Rules that keep work moving',
    'capabilities_intro' => 'You decide the rules. DotOne applies them every time a record is saved, so routine steps do not depend on someone remembering.',
    'capabilities' => [
        ['check', 'Approval chains', 'Route purchase orders, quotations and other documents to the right approver based on amount, discount or department.'],
        ['bell', 'Alerts', 'Notify the right people when stock is low, an order is late or a quality check fails.'],
        ['box', 'Automatic indents', 'When an item falls below its reorder level, a purchase indent is raised for the buying team.'],
        ['flow', 'Hand-offs between departments', 'A confirmed order can move to stores for picking, production for planning or accounts for billing.'],
        ['shield', 'Escalations', 'If an approval or task waits too long, it is escalated to the next person you have set.'],
        ['users', 'Role-based routing', 'Tasks go to roles, not just names, so work continues when someone is on leave.'],
    ],
    'workflow_intro' => 'A typical workflow is a set of small rules. Here is how a purchase moves from low stock to an approved order.',
    'workflow' => [
        ['Trigger', 'An item falls below its reorder level.'],
        ['Indent', 'DotOne raises a purchase indent for the buying team.'],
        ['Route', 'The PO is prepared and sent to the approver set for that amount.'],
        ['Escalate', 'If it is not approved in time, it goes to the next approver.'],
        ['Hand off', 'Once approved, it goes to the vendor and stores is told what to expect.'],
    ],
    'reports' => [
        'Pending approvals by person and age',
        'Escalated tasks',
        'Auto-raised indents',
        'Average approval time by document type',
        'Alerts raised and closed',
        'Hand-offs waiting between departments',
    ],
    'connected_intro' => 'Workflows run across modules, so a step finished in one department starts the next one in another.',
    'connected' => ['purchase-management', 'inventory-management', 'sales-management', 'production-management', 'quality-management', 'hrms'],
    'agent' => 'operations',
    'agent_questions' => [
        'Which approvals have been waiting for more than two days?',
        'Which orders are stuck between sales and stores?',
        'Who has the most pending tasks this week?',
    ],
    'faq' => [
        ['What kind of workflows can we automate?', 'Common ones are purchase and quotation approvals, low-stock indents, alerts on late orders or failed checks, and hand-offs from sales to stores, production and accounts.'],
        ['Do we need to write code?', 'No. Workflows are set up as rules on documents and roles. Our onboarding team helps you set up the first ones.'],
        ['What happens if an approver is away?', 'You can route tasks to roles and set escalations, so work moves to the next person if it waits too long.'],
        ['How does this relate to AI automation?', 'Workflows follow fixed rules. AI agents add judgement on top, such as spotting stuck work or drafting the next step. See [AI automation](/ai-automation).'],
    ],
    'cta_heading' => 'See one of your workflows automated',
    'cta_text' => 'Bring one approval or hand-off that slows you down today, and we will set it up in DotOne during a 30-minute demo.',
];
include __DIR__ . '/includes/templates/module.php';
